name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Push Docker Image to Docker Hub
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Login to Docker Hub
        id: docker-hub
        env:
          DOCKERHUB_USERNAME: ${{secrets.DOCKERHUB_USERNAME}}
          DOCKERHUB_PASSWORD: ${{secrets.DOCKERHUB_PASSWORD}}
        run: |
          echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin

      - name: Build and Tag Client Docker Image
        run: |
          docker build ./client -t ${{secrets.DOCKERHUB_USERNAME}}/client-app:latest

      - name: Build and Tag Server Docker Image
        run: |
          docker build ./server -t ${{secrets.DOCKERHUB_USERNAME}}/server-app:latest

      - name: Push Client Docker Image
        run: |
          docker push ${{secrets.DOCKERHUB_USERNAME}}/client-app:latest

      - name: Push Server Docker Image
        run: |
          docker push ${{secrets.DOCKERHUB_USERNAME}}/server-app:latest
