name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Docker Buildx for multi-platform builds
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Step 3: Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Step 4: Build and Push Frontend (Client) Image
    - name: Build and Push Frontend (Client) Image
      working-directory: ./client
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/frontend-client:latest .
        docker push ${{ secrets.DOCKER_USERNAME }}/frontend-client:latest

    # Step 5: Build and Push Backend (Server) Image
    - name: Build and Push Backend (Server) Image
      working-directory: ./server
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/backend-server:latest .
        docker push ${{ secrets.DOCKER_USERNAME }}/backend-server:latest

    # Step 6: Push Docker Compose-based images (optional)
    - name: Build and Push Full Application via Docker Compose
      run: |
        docker-compose -f ./docker-compose.yml build
        docker-compose -f ./docker-compose.yml push
