name: Build and Push Docker Images to Docker Hub

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: Check out the repo
      uses: actions/checkout@v4

    # Step 2: Login to Docker Hub
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}  # Use secret for username
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # Step 3: Build and Push Frontend (Client) Image
    - name: Build and Push Frontend (Client) Image
      uses: docker/build-push-action@v5
      with:
        context: ./client
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/docker-deploy-client:latest  # Use secret for username

    # Step 4: Build and Push Backend Image
    - name: Build and Push Backend  Image
      uses: docker/build-push-action@v5
      with:
        context: ./server
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/docker-deploy-server:latest  # Use secret for username
