name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        run: |
          docker login -u "${{ secrets.DOCKER_USERNAME }}" -p "${{ secrets.DOCKER_PASSWORD }}"

      - name: Build Client Image
        run: |
          cd client
          docker build -t ${{ secrets.DOCKER_USERNAME }}/taskflow-client:latest .

      - name: Push Client Image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/taskflow-client:latest

      - name: Build Server Image
        run: |
          cd server
          docker build -t ${{ secrets.DOCKER_USERNAME }}/taskflow-server:latest .

      - name: Push Server Image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/taskflow-server:latest
